### ISSUE TITLE
希望添加创建历史记录或账号登录

### ISSUE THREAD

**Issue by ESEAbsolute** [Nikaidou-Shinku/PastePlz#1]
刚刚创建了一个，之后回到了首页，发现我那个创建的找不到了 xwx

希望可以查看同 ip 下创建的所有内容，或者提供账号注册 / 登录然后查看本账号创建的内容。

**Comment by Nikaidou-Shinku** [comment]
PastePlz 开发的初衷是为了方便快捷地分享代码，而不是作为备忘录，所以没有考虑到历史记录方面的功能，短期内应该也不会有这样的计划。而已经发布的内容也不作长期有效保证，毕竟 PastePlz 只是一个临时的剪切板。

就像 Ubuntu Pastebin 需要登录才能发布内容之后，也没有提供查询历史记录的功能，希望理解 :)

**Comment by ESEAbsolute** [comment]
明白了 谢谢！
