### ISSUE TITLE
修改查看 paste 页的 css 样式

### ISSUE THREAD

**Issue by aberter0x3f** [Nikaidou-Shinku/PastePlz#2]
现在这个剪贴板创建 paste 页的代码框背景是白的，但是查看页的代码框背景是黑的，看上去非常瞎眼

**Comment by Nikaidou-Shinku** [comment]
你是对的，我会在未来（很快）加上选择代码高亮方式的功能。发件人: ***@***.*** ***@***.***> 代表 yzy-1 ***@***.***>发送时间: 2022年5月10日星期二 17:23收件人: Nikaidou-Shinku/PastePlz ***@***.***>抄送: Subscribed ***@***.***>主题: [Nikaidou-Shinku/PastePlz] 修改查看 paste 页的 css 样式 (Issue #2)

现在这个剪贴板创建 paste 页的代码框背景是白的，但是查看页的代码框背景是黑的，看上去非常瞎眼

**Comment by Nikaidou-Shinku** [comment]
你是对的，我会在未来（很快）加上选择代码高亮风格的功能。

**Comment by Nikaidou-Shinku** [comment]
Commit [9b83bf1](https://github.com/Nikaidou-Shinku/PastePlz/commit/9b83bf1fe6c33679e5a825aacdec0526ae0245b0) 加入了暗色主题（Dark theme）开关，代码高亮风格与主题保持一致。
