### ISSUE TITLE
背景颜色只会填充第一个屏幕的高度

### ISSUE THREAD

**Issue by aberter0x3f** [Nikaidou-Shinku/PastePlz#3]
当保存一个长度超过一个屏幕的文字到剪贴版的时候，剪贴板的背景颜色只会填充一个屏幕的高度。

当设置为深色模式的时候更为明显。

[![1661055894743.png](https://img-kysic-1258722770.file.myqcloud.com/8a15e8de70fc84f21acd2ef6474d74a6/8d140f4197d7c.png)](https://img-kysic-1258722770.file.myqcloud.com/8a15e8de70fc84f21acd2ef6474d74a6/8d140f4197d7c.png)

**Comment by Nikaidou-Shinku** [comment]
WOW! 我刚刚准备重构这个项目，居然就有 issue 了！

这个是已知的 bug，因为原代码已经略显难以维护（以及初期架构问题）所以一直没有动工。

重构后会修正的！

**Comment by Nikaidou-Shinku** [comment]
因为懒癌犯了，重构计划被搁置了很久。好在现在我想起来它了。

我花了两天时间重构了整个 PastePlz 的前后端，写了响应式代码来适配移动设备，拆分了页面并使用服务端渲染来加快访问速度……现在全新的 PastePlz v1 已经可用了，欢迎您继续使用！
